import = [
    "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
]

[font]
normal.family = "MesloLGS Nerd Font Mono"

#regular
size = 15

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

opacity = 0.9
decorations = "Buttonless"
